export const KAFKA_MODULE_OPTIONS = 'KAFKA_MODULE_OPTIONS';
export const TRANSPORT_CONFIG = 'TRANSPORT_CONFIG';
export const TRANSPORT_NAMESPACE = 'TRANSPORT_NAMESPACE';
export const SCHEMA_REGISTRY_OPTIONS = 'SCHEMA_REGISTRY_OPTIONS';
export const CONSUMER_DEFAULTS = 'CONSUMER_DEFAULTS';
export const CONNECTOR_NAME = 'CONNECTOR_NAME';
export const KAFKA_PRODUCER = 'KAFKA_PRODUCER';
