export const TRANSPORT_CONNECTOR_OPTIONS = 'TRANSPORT_CONNECTOR_OPTIONS';
export const TRANSPORT_CONFIG = 'TRANSPORT_CONFIG';
export const TRANSPORT_NAMESPACE = 'TRANSPORT_NAMESPACE';
export const SCHEMA_REGISTRY_OPTIONS = 'SCHEMA_REGISTRY_OPTIONS';
export const CONSUMER_DEFAULTS = 'CONSUMER_DEFAULTS';
export const MODULE_NAME = 'module_name';
export const KAFKA_PRODUCER = 'KAFKA_PRODUCER';
